# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: dd7865e78308610bfc9292c80e8c1a8bdb2b291539228b5a2615ce5c6693daa793edd418ea86b85bfeecc82ce289b78e974ee3462c1fed72241e2ed9aefd2094

test:
  secret_key_base: eca179c209528c3814d4260e0365daa5d8ba06c54abff0b39370091b55290653753fcaf38ce67dc8265df15d1c1aaac729042f50201648a446f950413ef553b4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
